# Generated by Django 4.1.3 on 2022-11-07 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vianda', '0003_alter_vianda_fecha_vianda_remove_vianda_tipo_plato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vianda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
